local M = {

    options = {
        { "Timer",          TIMER,  0 },
        { "BGFilled",       BOOL,   0 },
        { "Reserve",        VALUE,  20, 0, 40 },
        { "CalloutInt",     VALUE,  6,  1, 60 },
        { "Haptic",         BOOL,   1 },
        { "Mute",           CHOICE, 1,  { "None", "Voltage alerts", "Voltage and fuel alerts" } },
        { "StatsViewMode",  CHOICE, 2,  { "Never", "On disarmed", "On disconnected" } },
        { "VoltageDisplay", CHOICE, 1,  { "Cell voltage", "Battery voltage" } },
        { "CellSource",     CHOICE, 1,  { "FC config", "Manual" } },
        { "CellFull",       VALUE,  412, 0, 480 },
        { "CellLow",        VALUE,  345, 0, 440 },
        { "CellCritical",   VALUE,  330, 0, 440 },
        { "StartupDelay",   VALUE,  4,  1, 20 },
        { "LinkWarn",       BOOL,   1 },
        { "RQlyWarn",       VALUE,  50, 0, 100 },
        { "RQlyCrit",       VALUE,  30, 0, 100 },
        { "TopLeft",        CHOICE, 1,  { "Model image", "Timer" } },
        { "ColorScheme",    CHOICE, 1,  { "UltiDash", "by EdgeTX Theme" } },
        { "ShowRQly",       BOOL,   1 },
        { "ShowTQly",       BOOL,   1 },
        { "ShowTPWR",       BOOL,   1 },
        { "ShowTxV",        BOOL,   1 },
        { "PwrWarn",        BOOL,   1 },
        { "PwrWarnV",       VALUE,  90, 30, 500 },
        { "SkpWarn",        BOOL,   0 },
        { "SkpLimit",       VALUE,  50, 1, 2000 },
    },

    translate = function(name)
        local translations = {
            Timer = "Which timer to display",
            BGFilled = "Fill background color",
            Reserve = "Reserve capacity (%)",
            CalloutInt = "Callout interval (sec)",
            Haptic = "Vibrate on critical alerts",
            Mute = "Mute (voice and vibration)",
            StatsViewMode = "When to show statistics page",
            VoltageDisplay = "Voltage shown as",
            CellSource = "Cell thresholds from",
            CellFull = "Full cell voltage (cv, manual)",
            CellLow = "Low cell voltage (cv, manual)",
            CellCritical = "Critical cell voltage (cv, manual)",
            StartupDelay = "Startup cell-check delay (s)",
            LinkWarn = "Link/telemetry warnings",
            RQlyWarn = "Link quality warn (%)",
            RQlyCrit = "Link quality critical (%)",
            TopLeft = "Top-left area shows",
            ColorScheme = "Color scheme",
            ShowRQly = "Top bar: show RQly",
            ShowTQly = "Top bar: show TQly",
            ShowTPWR = "Bottom bar: show TPWR",
            ShowTxV = "Top bar: show TX voltage",
            PwrWarn = "Main power loss warning",
            PwrWarnV = "Power warn voltage (0.1V)",
            SkpWarn = "Skipped-packet warning",
            SkpLimit = "Skipped-packet limit",
        }
        return translations[name]
    end
}

return M
